"""add role attribute to user entity;add projectmember entity

Revision ID: 40b4e216e243
Revises: b15806417246
Create Date: 2026-02-26 07:49:20.684722

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '40b4e216e243'
down_revision: Union[str, Sequence[str], None] = '727944083d69'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
op.add_column(
    "users",
    sa.Column("role", sa.String(), nullable=False, server_default="member")
)    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'role')
    # ### end Alembic commands ###
